name: Build Plugin NWAPI

on:
  push:
    branches: [ master ]

env:
  # Para la version 10.2 el link de referencias tiene que ser este https://www.exiled.host/build_deps/Master.zip 
  # Pero si es para la beta https://exiled.host/build_deps/Dev.zip
  #EXILED_REFERENCES_URL: https://exiled.host/build_deps/Dev.zip
  #EXILED_REFERENCES_PATH: ${{ github.workspace }}/References
  DEPOT_DOWNLOADER_VERSION: 2.4.7
  SL_REFERENCES: D:\a\UltimateAfk\SCPSL_REFERENCES\SCPSL_Data\Managed
  UNITY_REFERENCES: D:\a\UltimateAfk\SCPSL_REFERENCES\SCPSL_Data\Managed
  SL_BRANCH: pluginapi-beta

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Download depot downloader
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path D:\a\UltimateAfk
        New-Item -ItemType Directory -Force -Path D:\a\UltimateAfk\DepotDownloader
        Invoke-WebRequest -Uri "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_${{ env.DEPOT_DOWNLOADER_VERSION }}/depotdownloader-${{ env.DEPOT_DOWNLOADER_VERSION }}.zip" -OutFile "D:\a\UltimateAfk\depotdownloader.zip"
        Expand-Archive -Path D:\a\UltimateAfk\depotdownloader.zip -PassThru -DestinationPath D:\a\UltimateAfk/DepotDownloader

    - name: Download SCPSL references.
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path D:\a\UltimateAfk\SCPSL_REFERENCES
        Start-Process -NoNewWindow -Wait -FilePath "D:\a\UltimateAfk\DepotDownloader\DepotDownloader.exe" -WorkingDirectory "D:\a\UltimateAfk\DepotDownloader" -ArgumentList '-app 996560','-beta nightly','-betapassword ${{ env.SL_BRANCH }}','-dir D:\a\UltimateAfk\SCPSL_REFERENCES','-filelist "${{ github.workspace }}\download-files.txt"'

    - name: Download NWAPIPermissionSystem.dll
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/CedModV2/NWAPIPermissionSystem/releases/download/0.0.3/NWAPIPermissionSystem.dll" -OutFile ${{ env.SL_REFERENCES }}/NWAPIPermissionSystem.dll
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Debug

    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: UltimateAFK
        path: ${{ github.workspace }}/bin/Debug/UltimateAFK.dll
        retention-days: 1